### ISSUE TITLE
class decorator to check for @final

### ISSUE THREAD

**Issue by tmasek** [mkorpela/overrides#12]
apparently I don't have enough SO reputation to just leave a comment there..

feature request:
have you thought about a class-level decorator that checks for @final decorators in parent classes, for all methods, not just those marked with @overrides? i'm thinking it will be easier to remember a single class-level decorator than it would be to try and mark every method with @overrides and work backwards to resolve issues..

**Comment by mkorpela** [comment]
I believe this is now done in version 2.4.

**Comment by tmasek** [comment]
awesome, thanks!!
