### ISSUE TITLE
[Question] Python's official lib `typing` implements `@final` and `@override` in 3.12

### ISSUE THREAD

**Issue by ParticleG** [mkorpela/overrides#126]
What's the difference between the official implementation and this lib's? Should I switch to official `typing` lib or stick to this lib?

**Comment by mkorpela** [comment]
Note that this package is ”the future” 10 years before it happened and also mentioned in the PEP for override https://peps.python.org/pep-0698/#runtime-override-checks-in-python

The package currently when I’m writing this has a pretty large user space and is hanging in the top 500 most downloaded pypi packages list. Large long time usage without changes means stability and reliability.

There are few differences:
- the typing versions do not check the override during module import.
- This package copies the docstrings from superclass
- It works if you can’t ensure that Python 3.12 or above is used

**Comment by ParticleG** [comment]
> the typing versions do not check the override during module import.

Thanks a lot. Then I'll stick to this library
