### ISSUE TITLE
Checking for subtype seems to cause issues

### ISSUE THREAD

**Issue by ruzzle** [mkorpela/overrides#128]
Given the following python code 

```python
from overrides import override
from abc import abstractmethod

class A:
    pass

class B(A):
    pass

class C:

    @abstractmethod
    def test(self, inp: A): ...

class D(C):

    @override
    def test(self, inp: B):
        print('test implementation')
```

Loading this python code results in the following:
```
TypeError: `D.test: inp must be a supertype of `<class 'override_issue.A'>` but is `<class 'override_issue.B'>`
```

Looking at the source code, it seems to me that the checking of subtypes seems erroneously swapped

**Comment by mkorpela** [comment]
Actually the input params are Contravariant. https://en.wikipedia.org/wiki/Covariance_and_contravariance_(computer_science)

Subtype should be able to handle any input that the super type gets.

One option if your thinking of abstract methods, is using generics. Generic T that is bound to type A. Then you can have class D where that T is B.
