### ISSUE TITLE
@overrides issue w/ typing.Generic and built-in types

### ISSUE THREAD

**Issue by dhorkin** [mkorpela/overrides#26]
Toy example that triggers the problem (tested in Python 3.7):
```Python
from typing import Generic, TypeVar

from overrides import overrides

class Foo:
    pass

T1 = TypeVar('T1')

class SuperClass(Generic[T1]):
    pass

# this class causes error, but ONLY w/ the @overrides annotation
class SubClass1(SuperClass[float]):
    @overrides  # gives wrong error message, even if defined in SuperClass
    def foo(self):
        pass

class SubClass2(SuperClass[Foo]):
    @overrides  # behaves as expected
    def foo(self):
        pass
```

This triggers the following:

> Traceback (most recent call last):
>   File "C:\Users\Dylan\Miniconda3\envs\test\lib\site-packages\overrides\overrides.py", line 165, in _get_base_class
>     obj = namespace[components[0]]
> KeyError: 'float'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:/Users/Dylan/.PyCharmCE2019.2/config/scratches/scratch_1.py", line 14, in <module>
>     class SubClass1(SuperClass[float]):
>   File "C:/Users/Dylan/.PyCharmCE2019.2/config/scratches/scratch_1.py", line 15, in SubClass1
>     @overrides  # gives wrong error message, even if defined in SuperClass
>   File "C:\Users\Dylan\Miniconda3\envs\test\lib\site-packages\overrides\overrides.py", line 58, in overrides
>     for super_class in _get_base_classes(sys._getframe(2), method.__globals__):
>   File "C:\Users\Dylan\Miniconda3\envs\test\lib\site-packages\overrides\overrides.py", line 75, in _get_base_classes
>     class_name_components in _get_base_class_names(frame)]
>   File "C:\Users\Dylan\Miniconda3\envs\test\lib\site-packages\overrides\overrides.py", line 75, in <listcomp>
>     class_name_components in _get_base_class_names(frame)]
>   File "C:\Users\Dylan\Miniconda3\envs\test\lib\site-packages\overrides\overrides.py", line 167, in _get_base_class
>     obj = namespace["__builtins__"][components[0]]
> TypeError: 'module' object is not subscriptable
> 
> Process finished with exit code 1

**Comment by mkorpela** [comment]
Fixed in version 2.1
