### ISSUE TITLE
Overriding ClassMethod Fails

### ISSUE THREAD

**Issue by ngoodman90** [mkorpela/overrides#30]
When overriding a classmethod, the override decorator isn't recognised.

```
@classmethod
@abstractmethod
def method(cls):
    pass

@classmethod
@overrides
def method(cls):
    return 1
```

AssertionError: Method method overrides but does not have @overrides decorator

**Comment by ngoodman90** [comment]
Possible solution:
In EnforceOverridesMeta add:
```
if isinstance(value, classmethod):
    value = value.__get__(None, dict)
```
Worked for me :)

**Comment by mkorpela** [comment]
Thanks @ngoodman90 might you want to make a pull request about this?
I can release the new version after that.
