### ISSUE TITLE
Missing type annotations

### ISSUE THREAD

**Issue by JoostFromMicrosoft** [mkorpela/overrides#37]
The `final` and `overrides` decorators do not contain type annotations. As a result, adding these decorators to functions breaks `mypy` type checking (the annotations are 'forgotten').

Adding the following type stubs would fix this:

```py
from typing import Any, Callable, TypeVar

_FuncT = TypeVar('_FuncT', bound=Callable[..., Any])

def final(method: _FuncT) -> _FuncT:
    ...
def overrides(method: _FuncT) -> _FuncT:
    ...
```

Note that there is a separate issue of a module and decorator sharing a name (`overrides`). Some care must be taken to avoid `mypy` getting confused by this. By putting the above stubs in `__init__.pyi` in an `overrides-stubs` package (installed with pip), this potential confusion was avoided.

**Comment by mkorpela** [comment]
Hi @JoostFromMicrosoft ,
I've started implementing this. I have not yet done mypy stubs for any of my projects.
So this is a bit new for me. Where should the overrides-stubs package be located (I now created stubs dir for the type stub __init__.pyi file)?

**Comment by JoostFromMicrosoft** [comment]
Hi @mkorpela. Thanks for taking a look! I implemented this as a PEP-561 stub-only package. This is a good way for third parties (like myself) to patch in type stubs, but is not the preferred way for package maintainers to distribute type information:

> ### Stub-only Packages
> For package maintainers wishing to ship stub files containing all of their type information, it is preferred that the *.pyi stubs are alongside the corresponding *.py files. However, the stubs can also be put in a separate package and distributed separately. Third parties can also find this method useful if they wish to distribute stub files.

https://www.python.org/dev/peps/pep-0561/#stub-only-packages

If you want to distribute with the package (as is recommended), I think you should be able to just add `py.typed` and the described `__init__.pyi` to your package.

That all being said, this is my setup:

```
type_stubs/
    |-overrides-stubs/
    |    |-__init__.pyi
    |-[other stubs packages]
    |-setup.py
```
Where `__init__.pyi` contains the code described in my OP. I then installed the `type_stubs` library using `pip`, allowing `mypy` to find it.

**Comment by mkorpela** [comment]
This is now done in 3.0.0
