### ISSUE TITLE
Classifiers are not enough to protect Python 2 users from latest version

### ISSUE THREAD

**Issue by rstakenborg** [mkorpela/overrides#40]
Classifiers are correctly stated, but these are only for browsing Pypi and are not used during installation:
https://github.com/mkorpela/overrides/blob/8cfef0064f9a09c5b7c8d6d7a152455f1de26209/setup.py#L29

Python3 should be declared as a python_requires:
https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires

Otherwise, Python2 installs 3.x.x, but receives a syntax error during import overrides:
https://github.com/mkorpela/overrides/blob/8cfef0064f9a09c5b7c8d6d7a152455f1de26209/overrides/overrides.py#L28

**Comment by mkorpela** [comment]
https://github.com/mkorpela/overrides/commit/bfbde10309c7691fc4e8738e4eddf67a4d8410f0 done
