### ISSUE TITLE
Class cannot subclass 'EnforceOverrides' (has type 'Any')

### ISSUE THREAD

**Issue by TylerYep** [mkorpela/overrides#47]
When I use mypy --strict, I get:
```
error: Class cannot subclass 'EnforceOverrides' (has type 'Any')
```

This error occurs because mypy --strict contains the --disallow-subclassing-any flag, which prevents subclasses that return Any from being subclassed with more specific type annotations, e.g.
```
class Player(EnforceOverrides):
    def __init__(self) -> None:
          pass
```

I've tried looking into this issue but I've gotten stuck. Maybe it has to do with adding type hints...

**Comment by mkorpela** [comment]
Might also be a bug in mypy? Thanks for looking into this issue @TylerYep !

**Comment by mkorpela** [comment]
Fixed in https://github.com/mkorpela/overrides/pull/57

**Comment by mkorpela** [comment]
It was not enough..

**Comment by mkorpela** [comment]
Now it is https://github.com/mkorpela/overrides/commit/1c93f79780c2fd38fdc0a5c276d74e0ead8a9fc0
