### ISSUE TITLE
@final vs pep-0591

### ISSUE THREAD

**Issue by zolyfarkas-fb** [mkorpela/overrides#49]
This library has a @final decorator as well, would be nice to document how does it square with:
https://www.python.org/dev/peps/pep-0591/#the-final-decorator

**Comment by mkorpela** [comment]
Hi,
Good point. It would be good to get these working in the same way.

**Comment by mkorpela** [comment]
https://docs.python.org/3/library/typing.html#typing.final
"There is no runtime checking of these properties." .. so should we just run this decorator in our final one?

**Comment by mkorpela** [comment]
Investigated this a bit more. Just wrapping the method in overrides.final to typing.final does not help.
Mypy or Pycharm are both completely clueless in this situation.

**Comment by mkorpela** [comment]
Documented for now that these are not the same thing.

**Comment by mkorpela** [comment]
"
FYI as of Python 3.11 `@final` will set a `.__final__` attribute at runtime: https://docs.python.org/3.11/library/typing.html#typing.final. This was also backported to `typing_extensions.final`.
" https://www.reddit.com/r/Python/comments/xmnv04/comment/irwow45/?utm_source=share&utm_medium=web2x&context=3

**Comment by mkorpela** [comment]
On 3.11 this is now same.
