### ISSUE TITLE
pycharm: 'overrides' is not callable

### ISSUE THREAD

**Issue by maggu2810** [mkorpela/overrides#5]
Hello,
I don't think that this is a problem with your code, but perhaps you could help me to solve this.

PyCharm offers a method to insect the code of a project.
If I am using your override annotation (thanks a lot), I get the following warning:
<pre>
Problem synopsis
      'overrides' is not callable (at line ...)
</pre>

One warning for each usage of the decorator.

I am also using "@abc.abstractmethod" decorators but there is no problem detected.

So, could you help me, why "abs" decorations are working without "problems" and your "overrides" raise such a warning?

I could ignore this IDE problem, as it is working, but it would be nice to get such stuff suppressed.

**Comment by jadolfbr** [comment]
In PyCharm 5, I get no warning, and clicking the decorator goes to the code.  Perhaps this is somehow fixed in the newer verision...

**Comment by mkorpela** [comment]
Thanks for the info. I'm closing this now.
