### ISSUE TITLE
Creating a method with the same name as a method in `EnforceOverridesMeta` raises

### ISSUE THREAD

**Issue by ashwin153** [mkorpela/overrides#51]
Because `register` is defined in `abc.ABCMeta` and `handle_special_value` is defined in `EnforceOverridesMeta`, the code incorrectly determines that classes that redefine these methods are missing an `@overrides` decorator. Instead, `EnforceOverridesMeta` should ignore methods that are missing an `@overrides` decorator if they are defined on `EnforceOverridesMeta`.

```python
class RegisterRepro(overrides.EnforceOverrides):
    def register(self):
        pass

# AssertionError: Method register overrides but does not have @overrides decorator
```

```python
class HandleSpecialValueRepro(overrides.EnforceOverrides):
    def handle_special_value(self):
        pass

# AssertionError: Method handle_special_value overrides but does not have @overrides decorator
```

**Comment by ashwin153** [comment]
I think you could fix this by checking that `base != EnforceOverrides` [here](https://github.com/mkorpela/overrides/blob/master/overrides/enforce.py#L135).

**Comment by ashwin153** [comment]
This doesn't work.

**Comment by ashwin153** [comment]
One hack would be to rename `handle_special_value` to `__handle_special_value` and `register` to `__register` in `EnforceOverridesMeta`. Making these methods private in `EnforceOverridesMeta` would make subclasses free to define methods with the same. What do you think? @mkorpela

**Comment by mkorpela** [comment]
Would make collision a lot less likely
