### ISSUE TITLE
Handle self of a subtype

### ISSUE THREAD

**Issue by mkorpela** [mkorpela/overrides#64]
`self` is a special param. Because of multiple inheritance self might not be able to actually obey normal requirements of subtype param to be contravariant [wikipedia Inheritance](https://en.wikipedia.org/wiki/Covariance_and_contravariance_(computer_science)#Inheritance_in_object-oriented_languages).
I believe that `self` should be assumed and allowed to be bound to current class. It is also safer not to complain.
( see https://github.com/mkorpela/overrides/issues/60#issuecomment-826261511 )

```Python
import abc
from typing import TypeVar

from overrides import EnforceOverrides, final, overrides

BaseType = TypeVar("BaseType", bound="A")
SubType = TypeVar("SubType", bound="B")


class A(abc.ABC, EnforceOverrides):
    @abc.abstractmethod
    def copy(self: BaseType) -> BaseType:
        """Copy an object."""


class B(A):
    @final
    @overrides
    def copy(self: SubType) -> SubType:  # TypeError: `~SubType` is not a `~BaseType`.
        return self.helper()  # For this to be valid, `self` must be typed as a subclass of `B`

    @abc.abstractmethod
    def helper(self: SubType) -> SubType:
        """Helper for copy(), specific to subclasses of `B`."""


class C(B):
    def helper(self) -> "C":
        return C()


C().copy()
```

**Comment by ashwin153** [comment]
We could use https://gist.github.com/MacHu-GWU/0170849f693aa5f8d129aa03fc358305#file-inspect_mate-py-L92 to check if a method is a `@staticmethod` and https://gist.github.com/MacHu-GWU/0170849f693aa5f8d129aa03fc358305#file-inspect_mate-py-L119 is a `@classmethod`, and then type check the first parameter differently depending on the kind of method. If the method is a `@staticmethod`, then type check the first parameter normally. If the method is a `@classmethod`, then check that the first parameter is a subtype of `Type[Self]`. Otherwise, check that the first parameter is a subtype of `Self`.

**Comment by mkorpela** [comment]
The example in this case actually is typewise unsafe.
`BaseType` can be something that `SubType` does not extent.
`BaseType` is bound to the super type of `SubType` but it can also be just another sibling type.

**Comment by ashwin153** [comment]
After playing around with it more, the check is actually much simpler than the articles I linked to.

```
# Return whether or not the method is bound to a class.
inspect.ismethod(method)
# Return whether or not the method is a classmethod.
isinstance(method, classmethod)
# Return whether or not the method is a staticmethod.
isinstance(method, staticmethod)
```

Therefore, we can skip type-checking the first parameter if `inspect.ismethod(method) and not isinstance(method, staticmethod)`. Does that sound reasonable?

**Comment by mkorpela** [comment]
Fixed in https://github.com/mkorpela/overrides/pull/70

**Comment by brentyi** [comment]
Is there any hope at full support for the TypeVar application that was originally cited?

Or more simply something like what was described in [PEP-484](https://www.python.org/dev/peps/pep-0484/#annotating-instance-and-class-methods), eg:
```
from typing import TypeVar

from overrides import overrides

T = TypeVar("T", bound="Copyable")


class Copyable:
    def copy(self: T) -> T:
        # return a copy of self
        pass


class C(Copyable):
    @overrides(check_at_runtime=True)
    def copy(self: "C") -> "C":
        pass


c = C()
c2 = c.copy()  # type here should be C
```
(note that this is unsafe the same way the original example was, but actually safe due to implied constraints on the type of `self`)

If not, it'd at least be very helpful (for me) to have this error suppressed so I can get this kind of thing checked by `mypy`. (which does not work with `overrides==3.1.0` but does with some recent type hint improvements within `overrides`)

**Comment by mkorpela** [comment]
```
Traceback (most recent call last):
  File "/Users/mkorpela/workspace/overrides/tmp/foo.py", line 22, in <module>
    c2 = c.copy()  # type here should be C
  File "/Users/mkorpela/workspace/overrides/overrides/overrides.py", line 85, in wrapper
    _validate_method(method, super_class, check_signature)
  File "/Users/mkorpela/workspace/overrides/overrides/overrides.py", line 108, in _validate_method
    ensure_signature_is_compatible(super_method, method)
  File "/Users/mkorpela/workspace/overrides/overrides/signature.py", line 39, in ensure_signature_is_compatible
    ensure_return_type_compatibility(super_type_hints, sub_type_hints, method_name)
  File "/Users/mkorpela/workspace/overrides/overrides/signature.py", line 148, in ensure_return_type_compatibility
    if not issubtype(sub_return, super_return):
  File "/Users/mkorpela/workspace/overrides/.venv/lib/python3.9/site-packages/typing_utils-0.0.3-py3.9.egg/typing_utils/__init__.py", line 274, in issubtype
    return _is_normal_subtype(normalize(left), normalize(right), forward_refs)
  File "/Users/mkorpela/workspace/overrides/.venv/lib/python3.9/site-packages/typing_utils-0.0.3-py3.9.egg/typing_utils/__init__.py", line 212, in _is_normal_subtype
    return _is_origin_subtype(left.origin, right.origin)
  File "/Users/mkorpela/workspace/overrides/.venv/lib/python3.9/site-packages/typing_utils-0.0.3-py3.9.egg/typing_utils/__init__.py", line 197, in _is_origin_subtype
    return issubclass(left, right)
TypeError: issubclass() arg 2 must be a class or tuple of classes
```

**Comment by mkorpela** [comment]
Some bug there is still - yoda

**Comment by mkorpela** [comment]
@brentyi how does your example by the way compare to Generics? https://github.com/python/mypy/blob/master/docs/source/generics.rst ..or well it seems like a local constraint because of self..
Complex thing :)

**Comment by mkorpela** [comment]
@brentyi I do agree that we have a bug in overrides but I think in your example a better implementation would be:
```Python
T = TypeVar("T", bound="Copyable")

class Copyable(Generic[T]):
    def copy(self: T) -> T:
        # return a copy of self
        pass


class C(Copyable['C']):
    pass

c = C()
c2 = c.copy()  
```

**Comment by mkorpela** [comment]
I think we need to fall back to ignoring super type when it is a TypeVar. Just assume that it matches.

**Comment by mkorpela** [comment]
TypeVar that basically is ”some concrete type that maybe bound” can not be checked against a concrete type. The correct result in Python is in my opinion ”unknown”.

**Comment by mkorpela** [comment]
This is now fixed in master https://github.com/mkorpela/overrides/commit/15d4ddf18b18081f5aa4b3bc0cd10b143210e618
