### ISSUE TITLE
Improve error messages

### ISSUE THREAD

**Issue by ashwin153** [mkorpela/overrides#66]
- Error messages should be more actionable.
- See #61.

**Comment by mkorpela** [comment]
I think general pattern of `TypeError: {class}.{method}: {description}` would be good.
Like
```
TypeError: B.methoda: parameter `x` is not present.
```

**Comment by mkorpela** [comment]
Done https://github.com/mkorpela/overrides/commit/da8250f9f58e7212719f92b0f84a8208011b3639
