### ISSUE TITLE
Override breaks when overriding a method with no type hints in third party library

### ISSUE THREAD

**Issue by harshit-py** [mkorpela/overrides#77]
Hi,

Starting v5.0.0 or greater, when you try to override a method which originally isn't supported for type hints, the overriding breaks. Caught in [AllenNLP](https://stackoverflow.com/questions/67326772/encountering-type-error-handling-when-running-allennlp-test-install) and [Grammarly/Gector](https://github.com/grammarly/gector/issues/100)

Steps to reproduce:

```python
from overrides import overrides
from typing import Any


class BaseClass:
    def do_something(self, arg1, arg2=None):
        pass

class ChildClass(BaseClass):

    @overrides
    def do_something(self, arg1:str, arg2:Any=None) -> Any:
        pass
``` 

throws the `TypeError`:

```
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    class ChildClass(BaseClass):
  File "main.py", line 12, in ChildClass
    def do_something(self, arg1:str, arg2:Any=None) -> Any:
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/overrides/overrides.py", line 88, in overrides
    return _overrides(method, check_signature, check_at_runtime)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/overrides/overrides.py", line 114, in _overrides
    _validate_method(method, super_class, check_signature)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/overrides/overrides.py", line 135, in _validate_method
    ensure_signature_is_compatible(super_method, method, is_static)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/overrides/signature.py", line 86, in ensure_signature_is_compatible
    ensure_all_positional_args_defined_in_sub(
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/overrides/signature.py", line 212, in ensure_all_positional_args_defined_in_sub
    raise TypeError(
TypeError: `ChildClass.do_something: arg1 must be a supertype of `<class 'inspect._empty'>` but is `<class 'str'>`
```

**Comment by mkorpela** [comment]
Thank you for the report.

**Comment by mkorpela** [comment]
@harshit-py after investigation I believe the raised error is correct. BaseClass accepts anything as the first argument also things that are not strings.

You can explicitly ignore signature check by typing:
```
@overrides(ignore_signature_check=True)
```

if you believe this is wrong then please explain more, so I can understand the problem better.

**Comment by harshit-py** [comment]
Hey what version is this available from? `@overrides(ignore_signature_check=True)` 
The reason I ask this is; the behaviour is different till v4.1.2, i.e overrides does not throw `TypeError` and works fine. It's only starting v5.0.0 that this issue comes up. 
And in  AllenNLP, this breaks because AllenNLP defines it's own [implementation](https://github.com/allenai/allennlp/blob/master/allennlp/common/params.py#L226) of a Dict sub classing `MutableMapping` from `collections.abc` which doesn't support type hints. Some of the issues directly related to this I could find are [this](https://github.com/sacdallago/bio_embeddings/issues/128) and [this](https://github.com/grammarly/gector/issues/100).
I hope I made the issue clear. Thanks.

**Comment by mkorpela** [comment]
Version 5.0.0 is first one with signature checks.

**Comment by mkorpela** [comment]
The TypeError thrown is in my opinion a valid problem. If a Superclass method signature allows passing any types to a param, then child must also.
I'll double check from mypy.

**Comment by mkorpela** [comment]
Sorry the argument name was wrong in my example: https://github.com/mkorpela/overrides/releases/tag/5.0.0

**Comment by mkorpela** [comment]
`@overrides(check_signature=False)` is the correct

**Comment by mkorpela** [comment]
@harshit-py I was thinking that there should be a PR to AllenNLP to fix / ignore the problem. Do you want to do it or should I?

**Comment by brentyi** [comment]
I submitted a PR with my view on this (as noted there, feel free to close): `def superclass_method(x):` should be treated slightly differently from `def superclass_method(x: Any) -> Any:`. Seems like this is what mypy does.

The current behavior makes it quite hard to use `overrides` when inheriting from unhinted third party libraries.

**Comment by mkorpela** [comment]
I think we could limit this to case were super class is in another package and untyped.
Those contain the AllenNLP case and are very hard to solve.

**Comment by mkorpela** [comment]
Released as https://pypi.org/project/overrides/6.1.0/

**Comment by mkorpela** [comment]
Thanks for contributions @harshit-py and @brentyi !
