### ISSUE TITLE
Error on builtin types

### ISSUE THREAD

**Issue by Victor333Huesca** [mkorpela/overrides#89]
Firstly, the new feature of type attribute check introduced in may is really neat and pushed further the importance of this module. Thanks a lot for that !

**_This is both an issue report and and a feature request._**

The current implementation relies on the inspect module which is nice but also has some quirks, specially with builtins. Any call to inspect on a builtin raises a "_**ValueError**: no signature found for builtin <...>_".

In practice this impact the signature check of the parent method when it comes from **native extensions** like _numpy_, _pandas_ or _PyQt_ !
Any inheritance of a builtin class with overrides of one of its methods using the `overrides` decorate lead to a failure.

Here is a reproducible example:
```python
import numpy as np
from overrides import overrides
class A(np.ndarray):
    @overrides
    def all(*args, **kwargs):
        return True # yeah pointless!
# Running this crashes... ofc removing the decorator solves the issue
```

- A simple fix would be to stop the error is to catch that error and ignore the type-check for this scenario (tested, requires only 3 or 4 lines of code). This can be improved by showing a message once when such error is encounter and ignoring other occurrences.
- A better fix would be to fallback on any __stubs__ associated with the super object if present and perform the type-checking on that signature as mypy does. This one is of course the way to go but will probably require more time to investigate.

**Comment by analog-cbarber** [comment]
I am using this to annotate overridden methods in pyqt, which worked fine using version 3.1.0. It just started breaking recently when I updated my conda environment (was 3.1 the latest version on conda-forge until recently?)

So I guess one workaround is to just use the old version otherwise it seems you have to turn off signature checking when this happens:

```python
@overrides(check_signature=False)
```

**Comment by mkorpela** [comment]
After the latest release 6.3.0 the issue mentioned here is no more. Thanks @tjsmart !
