### ISSUE TITLE
Pylance complains about missing stubs

### ISSUE THREAD

**Issue by alkatar21** [mkorpela/overrides#90]
However, I am not sure why that is the case
![grafik](https://user-images.githubusercontent.com/61387986/133457445-99a09b66-d7a5-4893-9b15-4209b50ee752.png)

Versions: overrides-6.1.0 typing-utils-0.1.0

**Comment by mkorpela** [comment]
Module contains py.typed file and should thus work .. https://github.com/mkorpela/overrides/blob/master/overrides/py.typed

**Comment by mkorpela** [comment]
Something similar(?) on pylance issue tracker https://github.com/microsoft/pylance-release/issues/555

**Comment by alkatar21** [comment]
Probably pylance has not updated after the update. pylance restart was not enough for some reason. After reinstalling the package, the warning is gone. Thanks anyway for the reply. I like this package.
