### ISSUE TITLE
Can't refine method typing if parent is typed as `typing.Any`

### ISSUE THREAD

**Issue by hal-314** [mkorpela/overrides#93]
Hello

First, thanks for your great work! Overrides library is very useful :) .

An example of the issue is:
```python
from overrides import overrides
from typing import Any

class Parent:
    def generic(self, a: Any):
        raise NotImplementedError()
        
class Child(Parent):
    
    @overrides
    def generic(self, a: int):
        return 4
```
Overrides raises the following error: ```TypeError: `Child.generic: a must be a supertype of `typing.Any` but is `<class 'int'>` ```
However, it's a valid typing for mypy. You can [here](https://mypy-play.net/?mypy=latest&python=3.8).

I'm facing this issue when using Pytorch Lightning. Their base class (LightningModule) defines:
```python
    def on_validation_batch_end(
        self,
        trainer: "pl.Trainer",
        pl_module: "pl.LightningModule",
        outputs: Optional[Union[torch.Tensor, Dict[str, Any]]],
        batch: Any,
        batch_idx: int,
        dataloader_idx: int,
    ) -> None:
        """Called when the validation batch ends."""
        pass
```
In my subclass, the batch will always be a `torch.Tensor`:

```python
    # In the subclass
    @overrides
    def on_validation_batch_end(
        self,
        trainer: "pl.Trainer",
        pl_module: "pl.LightningModule",
        outputs: torch.Tensor,  # <- this is allowed as it's one of the types in the union. 
        batch: torch.Tensor,  # <- this isn't allowed :/ . I must change to Union[Any, torch.Tensor] or use `@overrides(check_signature=False)`
        *args, **kwargs
    ) -> None:
        """Called when the validation batch ends."""
        pass
```
As a workaround, I'm disabling signature check as `@overrides(check_signature=False)`. It would be nice if `overrides` would allow overriding parameters typed as `Any` with any other type.

**Comment by ashwin153** [comment]
A method `A` overrides `B` if any valid invocation of `B` is a valid invocation of `A`. This is not the case with your example. For example, `parent.generic("foo")` is valid because `"foo"` is an `Any` but `child.generic("foo")` is not valid because `"foo"` is not an `int`. In other words, arguments need to be superclasses (contra-variance) and return types need to be subclasses (covariance) for a method to be a valid override.

I would recommend the following.


```python
from typing import Generic, TypeVar

T = TypeVar("T")

class Parent(Generic[T]):
  def generic(self, a: T) -> T:
    pass

class Child(Parent[int]):
  @overrides
  def generic(self, a: int) -> int:
    return a
```

**Comment by hal-314** [comment]
It makes sense. I was mistaken. I close the issue
