### ISSUE TITLE
Overrides breakes SOLID Liskov rule?

### ISSUE THREAD

**Issue by hubertqtf** [mkorpela/overrides#95]
My issue:
https://stackoverflow.com/questions/71500063/overrides-gets-error-is-not-a-valid-parameter
Basically, i have an automation test environment, and my method that overrides generic-abstract adds extra non-default argument. In case the argument has default, it works, but with positional one, EnforceOverrides fails.
I couldn't find simmilar issue, so I am writing here.

**Comment by mkorpela** [comment]
The answer in the stackoverflow is correct https://stackoverflow.com/a/71500109
You are breaking the substitution princible.
